### ISSUE TITLE
Add benchmarks to keep track of performance on sample PDFs

### ISSUE THREAD

**Issue by callegarimattia** [weareprestatech/hotpdf#11]
Using memray or other utils for profiling, we should have banchmarks running as a step in our current CI workflows.
We need to set as baseline the current profiling and set targets to reach for enhancing performance.
Also could useful to avoid unintended modifications that would slow down the package (we can set a threshold for mem/time consuption for new PRs)

**Comment by krishnasism** [comment]
PR: https://github.com/weareprestatech/hotpdf/pull/35
