### ISSUE TITLE
Making documentation more accessible

### ISSUE THREAD

**Issue by callegarimattia** [weareprestatech/hotpdf#5]
Options for keeping documentation organized are:

1. Hosting on [readthedocs.io](https://docs.readthedocs.io/en/stable/index.html) which is free and supports versioning and auto building from code (using doxygen for example) 
2. Having the docs for the stable version as a folder in the repo (accessible locally using an html)
3. exploring the wiki option provided by GitHub

@krishnasism @aptakhin what do you think?

**Comment by krishnasism** [comment]
Yes, please go ahead. 
For the internal implementation, I just uploaded generated HTML docs to Azure blob storage and made it public - but makes more sense to host it on readthedocs. 

Maybe you can check something out like Sphinx: https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html

**Comment by krishnasism** [comment]
I'll work on this @callegarimattia as discussed

**Comment by krishnasism** [comment]
Reopened because deployment still pending

**Comment by krishnasism** [comment]
Docs@ https://hotpdf.readthedocs.io/en/latest/
