### ISSUE TITLE
Loading a pdf with HotPdf constructor

### ISSUE THREAD

**Issue by callegarimattia** [weareprestatech/hotpdf#71]
**Feature**:
Make the initialization call to hotpdf `hotpdf_obj = HotPdf()` accept a string/file parameter and load directly a document.
```python
hotpdf_obj = HotPdf("my_document.pdf")
```
**Bug**:
Right now there is no explicit handling of loading a document in a hotpdf instance with an already loaded document.
We should add the expected behaviour in the docs and also support the reloading

@krishnasism

**Comment by krishnasism** [comment]
go ahead :)
